#+Title: CS/SE 3GC3 - Computer Graphics Final Project
#+Author: Alice Ip, Kexin Liu, Lily Lau, Meijing Li
#+Date: November 10, 2019
#+Options: toc:nil num:nil

* Current Features and Commands
One of the features that we have implemented is the room environment, that consists of a floor, walls, lighting and materials. Another implementation in our prototype is a obj reader function in the ingredients.cpp file that reads the obj file path passed to it, and extracts the appropriate information (mesh, texture, normals) into c++ vectors. These vectors are then used to load the objects into the room. The appropriate obj files for the ingredients/tools/textures were obtained from several sources (that are cited in the readme file), and edited as appropriate for our needs. 

** Commands
 - q - quit
 - 1 - View ingredients/objects to make salad recipe (default view)
 - 2 - View ingredients/objects to make curry recipe
 - 3 - View ingredients/objects to make steak recipe
 - up arrow - zoom out
 - down arrow - zoom in
 - left arrow - rotate left around kitchen counter
 - right arrow - rotate right around kitchen counter

** Recipe Details
- Soup - Potato, Tomato, Onion, Knife, Pot
- Salad - Mango, Orange, Banana, Knife
- Steak - Steak, Knife, Pan
   

* Features To Be Implemented/Fixed 
Some of the features that will be implemented in the future include the application of textures and materials on the objects. As well, we hope to optimization the object loading, to load only the necessary ingredients/tools required by the recipe the user selects. For example, if the user selects the curry option, we will only load the curry ingredients. In addition, there will be a timer displayed in the window that will inform the user of the remaining time to construct the recipe. A scoring system will be created, and also displayed when the timer runs out.

